"""empty message

Revision ID: 008a2a97bf29
Revises: 4ce556292115
Create Date: 2023-09-27 11:08:58.603606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008a2a97bf29'
down_revision = '4ce556292115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_products_consumer_id_consumers', type_='foreignkey')
        batch_op.drop_constraint('fk_products_supermarket_id_supermarkets', type_='foreignkey')
        batch_op.drop_column('supermarket_id')
        batch_op.drop_column('consumer_id')
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('consumer_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('supermarket_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_products_supermarket_id_supermarkets', 'supermarkets', ['supermarket_id'], ['id'])
        batch_op.create_foreign_key('fk_products_consumer_id_consumers', 'consumers', ['consumer_id'], ['id'])

    # ### end Alembic commands ###
