"""empty message

Revision ID: 551eb3a0570e
Revises: 
Create Date: 2023-09-26 11:53:04.718518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551eb3a0570e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supermarkets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('consumer_id', sa.Integer(), nullable=True),
    sa.Column('supermarket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consumer_id'], ['consumers.id'], name=op.f('fk_products_consumer_id_consumers')),
    sa.ForeignKeyConstraint(['supermarket_id'], ['supermarkets.id'], name=op.f('fk_products_supermarket_id_supermarkets')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consumer_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consumer_id'], ['consumers.id'], name=op.f('fk_carts_consumer_id_consumers')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_carts_product_id_products')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('supermarket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_prices_product_id_products')),
    sa.ForeignKeyConstraint(['supermarket_id'], ['supermarkets.id'], name=op.f('fk_prices_supermarket_id_supermarkets')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prices')
    op.drop_table('carts')
    op.drop_table('products')
    op.drop_table('supermarkets')
    op.drop_table('consumers')
    # ### end Alembic commands ###
