"""empty message

Revision ID: 59de84830e83
Revises: 53ec1c845cf2
Create Date: 2023-09-28 12:24:06.564789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59de84830e83'
down_revision = '53ec1c845cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
