"""empty message

Revision ID: a65e1b065ad3
Revises: e31735c6d183
Create Date: 2023-09-26 17:48:22.949850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65e1b065ad3'
down_revision = 'e31735c6d183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('label')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
